### ISSUE TITLE
Liveness and readnees dont work when use  flask-healthz

### ISSUE THREAD

**Issue by patsevanton** [fedora-infra/flask-healthz#2]
Hello! Thanks for flask-healthz!
I try use flask-healthz.
I dont know where use function readiness.
Code:

```
from flask_healthz import healthz
from flask_healthz import HealthError

app = Flask(__name__)
app.register_blueprint(healthz, url_prefix="/healthz")

def liveness():
    pass

def readiness():
    try:
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///collection.db?check_same_thread=False'
    except Exception:
        raise HealthError("Can't connect to the database")

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config["SQLALCHEMY_ECHO"] = True
db = SQLAlchemy(app)

```

Log:
```
/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy/__init__.py:813: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
```

helm
```
      containers:
....................
          ports:
            - name: http-5000
              containerPort: 5000
              protocol: TCP
            - name: http-80
              containerPort: 80
              protocol: TCP
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
```
